/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    api(project(":siddhi-core"))
    api(project(":siddhi-annotations"))
    api(libs.org.apache.maven.maven.plugin.api)
    api(libs.org.apache.maven.plugin.tools.maven.plugin.annotations)
    api(libs.org.freemarker.freemarker.gae)
    api(libs.org.yaml.snakeyaml)
    api(libs.org.apache.maven.maven.core)
    api(libs.commons.io.commons.io)
}

description = "Siddhi Documentation Generator"
