/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "siddhi"
include(":performance-samples")
include(":siddhi-annotations")
include(":siddhi-doc-gen")
include(":siddhi-core")
include(":io.siddhi.feature")
include(":siddhi-query-compiler")
include(":siddhi-service")
include(":coverage-reports")
include(":siddhi-core-doc-gen")
include(":quick-start-samples")
include(":siddhi-query-api")
include(":siddhi-samples")
project(":performance-samples").projectDir = file("modules/siddhi-samples/performance-samples")
project(":siddhi-annotations").projectDir = file("modules/siddhi-annotations")
project(":siddhi-doc-gen").projectDir = file("modules/siddhi-doc-gen")
project(":siddhi-core").projectDir = file("modules/siddhi-core")
project(":io.siddhi.feature").projectDir = file("modules/siddhi-feature")
project(":siddhi-query-compiler").projectDir = file("modules/siddhi-query-compiler")
project(":siddhi-service").projectDir = file("modules/siddhi-service")
project(":siddhi-core-doc-gen").projectDir = file("modules/siddhi-core/siddhi-core-doc-gen")
project(":quick-start-samples").projectDir = file("modules/siddhi-samples/quick-start-samples")
project(":siddhi-query-api").projectDir = file("modules/siddhi-query-api")
project(":siddhi-samples").projectDir = file("modules/siddhi-samples")
