/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    api(project(":siddhi-query-api"))
    api(project(":siddhi-query-compiler"))
    api(project(":siddhi-annotations"))
    api(libs.org.apache.logging.log4j.log4j.api)
    api(libs.org.apache.logging.log4j.log4j.core)
    api(libs.org.slf4j.slf4j.simple)
    api(libs.org.wso2.orbit.com.lmax.disruptor)
    api(libs.com.google.guava.guava)
    api(libs.org.quartz.scheduler.quartz)
    api(libs.io.dropwizard.metrics.metrics.core)
    api(libs.com.google.code.gson.gson)
    api(libs.com.jayway.jsonpath.json.path)
    api(libs.org.eclipse.osgi.org.eclipse.osgi.services)
    api(libs.org.osgi.org.osgi.core)
    api(libs.org.yaml.snakeyaml)
    api(libs.javax.annotation.javax.annotation.api)
    api(libs.org.wso2.orbit.javax.xml.bind.jaxb.api)
    api(libs.com.sun.xml.bind.jaxb.impl)
    api(libs.org.apache.geronimo.specs.geronimo.activation.v1.v1.spec)
    api(libs.com.sun.istack.istack.commons.runtime)
    api(libs.com.sun.activation.javax.activation)
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(libs.org.testng.testng)
}

description = "Siddhi Core"

tasks.named<Test>("test") {
    useTestNG()
}
