/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    api(project(":siddhi-query-api"))
    api(project(":siddhi-query-compiler"))
    api(project(":siddhi-core"))
    api(libs.org.apache.logging.log4j.log4j.api)
    api(libs.org.antlr.antlr4.runtime)
    api(libs.org.wso2.orbit.com.lmax.disruptor)
}

description = "Siddhi Quick Start Samples"
