/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.atteo.classindex.classindex)
}

description = "Siddhi Annotations"
