/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    api(libs.org.apache.logging.log4j.log4j.api)
    testImplementation(libs.org.testng.testng)
}

description = "Siddhi Query API"

tasks.named<Test>("test") {
    useTestNG()
}
