/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.osgi.org.osgi.core)
    api(libs.org.eclipse.osgi.org.eclipse.osgi.services)
    api(libs.org.apache.logging.log4j.log4j.slf4j.impl)
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.antlr.antlr4.runtime)
    api(project(":siddhi-query-api"))
    api(project(":siddhi-core"))
    api(project(":siddhi-query-compiler"))
    api(project(":siddhi-annotations"))
    api(libs.org.wso2.orbit.com.lmax.disruptor)
    api(libs.com.google.guava.guava)
    api(libs.org.quartz.scheduler.quartz)
    api(libs.io.dropwizard.metrics.metrics.core)
    api(libs.org.apache.commons.commons.lang3)
}

description = "Siddhi Feature"
