/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    api(libs.org.apache.logging.log4j.log4j.api)
    api(libs.com.google.code.gson.gson)
    api(project(":siddhi-query-api"))
    api(project(":siddhi-core"))
    api(project(":siddhi-query-compiler"))
    api(project(":siddhi-annotations"))
    api(libs.org.wso2.msf4j.msf4j.all)
    api(libs.javax.servlet.servlet.api)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.joda)
    testImplementation(libs.org.testng.testng)
}

description = "Siddhi As a Service"

tasks.named<Test>("test") {
    useTestNG()
}
