/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.wso2.org/nexus/content/groups/wso2-public/")
    }

    maven {
        url = uri("https://maven.wso2.org/nexus/content/repositories/releases/")
    }

    maven {
        url = uri("https://maven.wso2.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/releases/")
    }
}

group = "io.siddhi"
version = "5.1.31-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
