/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":siddhi-query-api"))
    api(libs.org.apache.logging.log4j.log4j.api)
    api(libs.org.mvel.mvel2)
    api(libs.org.antlr.antlr4.runtime)
    testImplementation(libs.org.testng.testng)
}

description = "Siddhi Query Compiler"

tasks.named<Test>("test") {
    useTestNG()
}
